TRAITS = {
  "elPrimo1",
  "elPrimo2",
  "elPrimo3",
  "Bea1",
  "Lola1",
  "Lola2",
  "Lola3",
  "Lola4",
  "Angelo1",
  "Angelo2",
  "Nita1",
  "Nita2",
  "Nita3",
  "Penny1",
  "Penny2",
  "Griff1",
  "Griff2",
  "Max1",
  "Tick1",
  "Tick2",
  "Frank1",
  "Frank2",
  "Frank3",
  "Spike1",
  "Spike2",
  "Spike3",
  "Gale1",
  "Shelly1",
  "Shelly2",
  "Shelly3",
  "Crow1",
  "Crow2",
  "Bo1",
  "Bo2",
  "Carl1",
  "Melodie1",
  "Melodie2",
  "Poco1",
  "Brock1",
  "Brock2",
  "Meg1",
  "Meg1_Transform",
  "Meg2_Transform",
  "Colt1",
  "Colt2",
  "Sprout1",
  "Sprout2",
  "Sprout3",
  "Sprout4",
  "Ruffs1",
  "Ruffs2",
  "Ruffs3",
  "Gray1",
  "Gray2",
  "Squeak1",
  "Mandy1",
  "Mandy2",
  "Hank1",
  "Rosa1",
  "Rosa2",
  "Rico1",
  "Rico2",
  -- "Eve1",
  "Belle1",
  "Belle2",
  "Belle3",
  "Belle4",
  "Ash1",
  "Ash2",
  "ASh3",
  "Piper1",
  "Piper2",
  "Janet1",
  "Janet2",
  "Buzz1",
  "Buzz2",
  "Buzz3",
  "Grom1",
  "Grom2",
  "Bonnie1",
  "Bonnie2",
  "Bonnie3",
  "Carl2",
  "Emz1",
  "Stu1",
  "8bit1",
  "8bit2",
  "8bit3",
  "Gene1",
  "Gene2",
  "Gene3",
  "Gene4",
  "Gene5",
  "Gene6",
  "Berry1",
  "Charlie1",
  "Bull1",
  "Jessie1",
  "Jessie2",
  "Jessie3",
  "Finx1",
  "Kenji1",
  "Juju1",
  "Juju2",
  "Lily1",
  "Lily2",
  "Lily3",
  "Lily4",
  "Barley1",
  "Leon1",
  "Leon2",
  "Leon3",
  "Leon4",
  "Leon5",
  "Tara1",
  "Tara2",
  "Tara3",
  "Tara4",
  "Gus1",
  "Gus2",
  "Gus3",
  "Olli1",
  "Olli2",
  "MrP1",
  "Draco1",
  "Amber1",
  "Amber2",
  "Amber3",
  "Byron1",
  "Byron2",
  "Edgar1",
  "Edgar2",
  "Fang1",
  "Fang2",
  "Fang3",
  "Meeple1",
  "Meeple2",
  "Meeple3",
  "Meeple4",
  "Meeple5",
  "Meeple6",
  "Meeple7",
  "Colette1",
  "Colette2",
  "Shade1",
  "Shade2",
  "Surge1",
  "Surge2",
  "Jae1",
  "Jae2",
  "Mortis1",
  "Moe1",
  "Moe1_Transform",
  "Moe2",
  "Maisie1",
  "Maisie2",
  "Maisie3",
  "Maisie4",
  "Maisie5",
  "Maisie6",
  "Maisie7",
  "Pearl1",
  "Pearl2",
  "Pearl3",
  "Penny4",
  "Tick3",
  "Angels1_1",
  "Angels1_2",
  "Angels2_1",
  "Angels2_2",
  "Angels3_1",
  "Angels4_1",
  "Angels4_2",
  "Angels5_1",
  "Angels5_2",
  "Angels6_1",
  "Angels7_1",
  "Angels8_1",
  "Angels8_2",
  "Demons1_1",
  "Demons1_2",
  "Demons1_3",
  "Demons2_1",
  "Demons2_2",
  "Demons3_1",
  "Demons3_2",
  "Demons4_1",
  "Demons5_1",
  "Demons6_1",
  "Demons6_2",
  "Demons7_1",
  "Demons8_1",
  "Demons8_2",
  "DuplicatorPet1",
  "ColtSpeedSp",
  "R_MaxHp_S",
  "R_MaxHp_E",
  "R_MaxHp_L",
  "R_MaxHp_Absolute_S",
  "R_MaxHp_Absolute_E",
  "R_MaxHp_Absolute_L",
  "R_MaxHp_Absolute_ULTRA",
  "R_MaxHp_Absolute_Mini_S",
  "R_MaxHp_Absolute_Mini_E",
  "R_MaxHp_Absolute_Mini_L",
  "R_Reload_S",
  "R_Reload_E",
  "R_Reload_L",
  "R_Reload_Mini_S",
  "R_Reload_Mini_E",
  "R_Reload_Mini_L",
  "R_MoveSpeed_S",
  "R_MoveSpeed_E",
  "R_MoveSpeed_L",
  "R_MoveSpeed_Max_L",
  -- "R_MoveSpeed_WithPet_S",
  -- "R_MoveSpeed_WithPet_E",
  -- "R_MoveSpeed_WithPet_L",
  "R_MoveSpeed_Mini_S",
  "R_MoveSpeed_Mini_E",
  "R_MoveSpeed_Mini_L",
  "R_Damage_S",
  "R_Damage_E",
  "R_Damage_L",
  "R_Damage_ULTRA",
  "R_Damage_Mini_S",
  "R_Damage_Mini_E",
  "R_Damage_Mini_L",
  "R_SuperRate_S",
  "R_SuperRate_E",
  "R_SuperRate_L",
  "R_HCRate_S",
  "R_HCRate_E",
  "R_HCRate_L",
  "R_SuperRate_Mini_S",
  "R_SuperRate_Mini_E",
  "R_SuperRate_Mini_L",
  "R_HCRate_Mini_S",
  "R_HCRate_Mini_E",
  "R_HCRate_Mini_L",
  "R_AttackRange_E",
  "R_AttackRange_L",
  "R_AttackRange_ULTRA",
  "R_AttackRange_Max_L",
  "R_AttackRange_Mini_L",
  "R_AttackRange_Cone_E_1",
  "R_AttackRange_Cone_E_2",
  "R_AttackRange_Cone_E_3",
  "R_AttackRange_Cone_L_1",
  "R_AttackRange_Cone_L_2",
  "R_AttackRange_Cone_L_3",
  "R_AttackRange_Cone_Mini_L_1",
  "R_AttackRange_Cone_Mini_L_2",
  "R_AttackRange_Cone_Mini_L_3",
  "R_ProjectileSpeed_S",
  "R_ProjectileSpeed_E",
  "R_ProjectileSpeed_L",
  "R_ProjectileSpeed_Max_S",
  "R_ProjectileSpeed_Max_E",
  "R_ProjectileSpeed_Max_L",
  "R_GadgetCooldown_S",
  "R_GadgetCooldown_E",
  "R_GadgetCooldown_L",
  "R_GadgetCooldown_Mini_S",
  "R_GadgetCooldown_Mini_E",
  "R_GadgetCooldown_Mini_L",
  "R_BulletSize_S",
  "R_BulletSize_E",
  "R_BulletSize_L",
  "R_BulletSize_ULTRA",
  "R_BulletSize_Mini_S",
  "R_BulletSize_Mini_E",
  "R_BulletSize_Mini_L",
  "R_BulletSizeArea_Mini_WithItem_S",
  "R_BulletSizeArea_Mini_WithItem_E",
  "R_BulletSizeArea_Mini_WithItem_L",
  "R_AreaEffectSize_S",
  "R_AreaEffectSize_E",
  "R_AreaEffectSize_L",
  "R_AreaEffectSize_ULTRA",
  "R_AreaEffectSize_Mini_S",
  "R_AreaEffectSize_Mini_E",
  "R_AreaEffectSize_Mini_L",
  "R_AreaEffectSize_Melee_S",
  "R_AreaEffectSize_Melee_E",
  "R_AreaEffectSize_Melee_L",
  "R_AreaEffect_BulletSize_S_1",
  "R_AreaEffect_BulletSize_S_2",
  "R_AreaEffect_BulletSize_E_1",
  "R_AreaEffect_BulletSize_E_2",
  "R_AreaEffect_BulletSize_L_1",
  "R_AreaEffect_BulletSize_L_2",
  "R_BulletSizeThrower_S",
  "R_BulletSizeThrower_E",
  "R_BulletSizeThrower_L",
  "R_AreaEffectSizeThrower_S",
  "R_AreaEffectSizeThrower_E",
  "R_AreaEffectSizeThrower_L",
  "R_BulletSizeThrower_Mini_S",
  "R_BulletSizeThrower_Mini_E",
  "R_BulletSizeThrower_Mini_L",
  "R_AreaEffectSizeThrower_Mini_S",
  "R_AreaEffectSizeThrower_Mini_E",
  "R_AreaEffectSizeThrower_Mini_L",
  "R_DamageReduction_S",
  "R_DamageReduction_E",
  "R_DamageReduction_L",
  "R_DamageReduction_Max_L",
  "R_DamageReduction_Effect_E",
  "R_DamageReduction_Effect_L",
  "R_DamageReduction_Mini_S",
  "R_DamageReduction_Mini_E",
  "R_DamageReduction_Mini_L",
  "R_LifeSteal_S",
  "R_LifeSteal_E",
  "R_LifeSteal_L",
  "R_LifeSteal_Mini_S",
  "R_LifeSteal_Mini_E",
  "R_LifeSteal_Mini_L",
  "R_LifeSteal_Pet_S",
  "R_LifeSteal_Pet_E",
  "R_LifeSteal_Pet_L",
  "R_RegenFaster",
  "R_ConsShield_Mini",
  "R_ConsShield",
  "R_SpawnBushOnMove",
  "R_SpawnBushOnAttack_L",
  "R_HealOnKill",
  "R_InvisibleOnKill",
  "R_PowerCubeOnUlti",
  "R_HealOnMove",
  "R_SpeedUpOnAtk",
  "R_SpeedUpOnSuper",
  "R_KnockbackOnTakeDmg",
  "R_SeeThroghtBushOnSuper",
  "R_SlowDownOnHit",
  "R_PoisonOnHit_S",
  "R_PoisonOnHit_E",
  "R_PoisonOnHit_L",
  "R_BurnOnHit_S",
  "R_BurnOnHit_E",
  "R_BurnOnHit_L",
  "R_BurnOnHit_Hold_S",
  "R_BurnOnHit_Hold_E",
  "R_BurnOnHit_Hold_L",
  "R_AutoChargeUlti_E",
  "R_AutoChargeUlti_L",
  "R_AutoChargeUlti_Max_L",
  "R_AutoChargeUlti_Max_E",
  "R_AutoChargeUlti_Sam_E",
  "R_HomeInOnAtk_1",
  "R_HomeInOnAtk_2",
  "R_HomeInOnAtk_3",
  "R_HomeInOnAtk_4",
  "R_HomeInOnAtk_Max_1",
  "R_HomeInOnUlti_1",
  "R_HomeInOnUlti_2",
  "R_HomeInOnUlti_3",
  "R_HomeInOnUlti_4",
  "R_HomeInOnAtk_Melee_1",
  "R_HomeInOnAtk_Melee_2",
  "R_HomeInOnAtk_Melee_3",
  "R_HomeInOnAtk_Melee_4",
  "R_DestroyEnvironment",
  "R_PassEnvironment",
  "R_PierceCharacter",
  "R_HealBuff_S",
  "R_HealBuff_E",
  "R_HealBuff_L",
  "R_HealBuff_Mini_S",
  "R_HealBuff_Mini_E",
  "R_HealBuff_Mini_L",
  "R_VisionInBush_S",
  "R_VisionInBush_E",
  "R_VisionInBush_L",
  "R_MoveSpeedInBush_S",
  "R_MoveSpeedInBush_E",
  "R_MoveSpeedInBush_Mini_E",
  "R_PowerCubeOnKill",
  "R_SpeedUpOnGadget_S",
  "R_PowerCubeEffective_E",
  "R_PowerCubeEffective_L",
  "R_PowerCubeDouble_L",
  "R_PowerCubeOnStart_S",
  "R_PowerCubeOnStart_E",
  "R_PowerCubeOnStart_L",
  "R_PowerCubeOnKillDouble_L",
  "R_HighHealthDamage_L",
  "R_LowHealthDamage_L",
  "R_LowHealthDamage_Mini_L",
  "R_LowHealthDamage_E",
  "R_ChargeSuperOnStart_S",
  "R_ChargeSuperOnStart_E",
  "R_ChargeHCOnStart_E",
  "R_ChargeHCOnStart_Mini_L",
  "R_ChargeHCOnStart_L",
  "R_FireBallAround_E",
  "R_FireBallAround_L",
  "R_DashSpeed_Mini_E",
  "R_DashSpeed_E",
  "R_DashSpeed_Mini_L",
  "R_PetMoveSpeed_S",
  "R_PetMoveSpeed_E",
  "R_PetMaxHP_S_1",
  "R_PetMaxHP_S_2",
  "R_PetMaxHP_E_1",
  "R_PetMaxHP_E_2",
  "R_PetMaxHP_L_1",
  "R_PetMaxHP_L_2",
  "R_PetNumber_L_1",
  "R_PetNumber_L_2",
  "R_ShootTwice_MainAtk_L_1",
  "R_ShootTwice_MainAtk_L_2",
  "R_ShootTwice_Throw_L",
  "R_TriggerSuper_MoreTimes_Pet_L_1",
  "R_TriggerSuper_MoreTimes_Pet_L_2",
  "R_TriggerSuper_MoreTimes_1_L",
  -- "R_Eve_TriggerSuper_MoreTimes_L_1",
  -- "R_Eve_TriggerSuper_MoreTimes_L_2",
  "R_Boomerang_L",
  "R_ChargeUpSpeed_L",
  "R_Spread_L",
  "R_DOT_E",
  "R_DOT_L",
  "R_Berry_L",
  "R_Lumi_L",
  "R_Nita_L",
  "R_Bull_L",
  "R_Rico_Bounce_S_1",
  "R_Rico_Bounce_S_2",
  "R_Rico_Bounce_S_3",
  "R_Rico_Bounce_S_4",
  "R_Rico_Bounce_E_1",
  "R_Rico_Bounce_E_2",
  "R_Rico_Bounce_E_3",
  "R_Rico_Bounce_E_4",
  "R_Rico_Bounce_L_1",
  "R_Rico_Bounce_L_2",
  "R_Rico_Bounce_L_3",
  "R_Rico_Bounce_L_4",
  "R_Ruff_Bounce_S_1",
  "R_Ruff_Bounce_S_2",
  "R_Ruff_Bounce_E_1",
  "R_Ruff_Bounce_E_2",
  "R_Ruff_Bounce_L_1",
  "R_Ruff_Bounce_L_2",
  "R_Gus_L_1",
  "R_Gus_L_2",
  "R_Gus_L_3",
  "R_Brock_L",
  "R_Mortis_Dash_E_1",
  "R_Mortis_Dash_E_2",
  "R_Mortis_Dash_L_1",
  "R_Mortis_Dash_L_2",
  "R_Tick_BulleNumber_E",
  "R_Tick_BulleNumber_L",
  "R_Shelly_L_1",
  "R_Shelly_L_2",
  "R_Hank_L",
  "R_Primo_L",
  "R_Draco_Super_L",
  "R_Barley_Slow_L",
  "R_Carl_Reload_L",
  "R_Emz_Area_L",
  "R_8Bit_Speed_L",
  "R_Frank_HP_L",
  "R_Angelo_Area_L",
  "R_Ash_PetNumber_L_1",
  "R_Ash_PetNumber_L_2",
  "R_Eve_PetNumber_L_1",
  "R_Eve_PetNumber_L_2",
  "R_Poco_Heal_L",
  "R_Meeple_HomeInMore_L",
  "R_Angelo_HoldTime_L",
  "R_Gale_MoreBullet_S",
  "R_Gale_MoreBullet_E_1",
  "R_Gale_MoreBullet_E_2",
  "R_Gale_MoreBullet_L_1",
  "R_Gale_MoreBullet_L_2",
  "R_Dynamike_Delay_L",
  "R_Olli_Bullet_L",
  "R_Olli_Spread_L",
  "R_Janet_ActiveTime_L",
  "R_Buster_ActiveTime_L",
  "R_Chuck_Super_E",
  "R_Gene_SuperRange_L",
  "R_Bea_Shield_L",
  "R_Byron_StatusEffect_L",
  "R_Spike_BulletMore_E",
  "R_Spike_BulletMore_L",
  "R_Sprout_GadgetCooldown_L",
  "R_Charlie_Spider_L",
  "R_Bo_InfinateMine_L",
  "R_Codilus_MainAtk_L",
  "R_Shade_SuperLastTime_L",
  "R_Melodie_Notes_L",
  "R_Buzz_SuperRange_L_1",
  "R_Buzz_SuperRange_L_2",
  "R_Bo_MainAtkMore_L",
  "R_Squeak_SpawnAreaE_L",
  "R_Colt_MoreBullet_L",
  "R_Nani_Bullets_L_1",
  "R_Nani_Bullets_L_2",
  "R_Nani_Super_E",
  "R_Nani_Super_L",
  "R_Hank_Range_S_1",
  "R_Hank_Range_S_2",
  "R_Hank_Range_S_3",
  "R_Hank_Range_E_1",
  "R_Hank_Range_E_2",
  "R_Hank_Range_E_3",
  "R_Hank_Range_L_1",
  "R_Hank_Range_L_2",
  "R_Hank_Range_L_3",
  "R_Add_Bullets_BasicAttack_ULTRA_1",
  "R_Add_Bullets_BasicAttack_ULTRA_2",
  "R_Add_Bullets_BasicAttack_L_1",
  "R_Add_Bullets_BasicAttack_L_2",
  "R_Kit_PowerCube_E",
  "R_Mina_Shield_L",
  "R_Chuck_Pole_E",
  "R_Chuck_Pole_L",
  "R_Clancy_Level_L",
  "R_Kit_AttackRange_L_1",
  "R_Kit_AttackRange_L_2",
  "R_Kit_AttackRange_L_3",
  "R_Shade_AttackRange_L_1",
  "R_Shade_AttackRange_L_2",
  "R_Otis_ActiveTime_L",
  "R_PowerCubeOnStart_ULTRA",
  "R_MoveSpeed_ULTRA",
  "ActorPlaceholderTrait",
  "DemogorgonLifeSteal",
  "R_God_ScaleUp",
  "R_God_Max_ScaleUp",
  "R_Leon_Super_L",
  "R_Bibi_Range_L_1",
  "R_Bibi_Range_L_2",
  "R_MaxHp_Absolute_Mini_Mini_S",
  "R_MaxHp_Absolute_Mini_Mini_E",
  "R_MaxHp_Absolute_Mini_Mini_L",
  "R_GadgetCooldown_Mini_Min_S",
  "R_GadgetCooldown_Mini_Min_E",
  "R_GadgetCooldown_Mini_Min_L",
  "R_HCTime_L",
  "R_MoveSpeed_Mini_Mini_S",
  "R_MoveSpeed_Mini_Mini_E",
  "R_MoveSpeed_Mini_Mini_L",
  "R_Frank_Scale_S",
  "R_Frank_Scale_E",
  "R_Frank_Scale_L",
  "R_Melodie_Notes_E",
  "R_BulletSize_Max_S",
  "R_BulletSize_Max_E",
  "R_BulletSize_Max_L",
  "R_Janet_ActiveTime_E",
  "R_Frank_SpeedDown_S",
  "R_Frank_SpeedDown_E",
  "R_Frank_SpeedDown_L",
  "R_MoveSpeedInBush_Mini_S",
  "R_Kaze_EffectSize_S",
  "R_Kaze_EffectSize_E",
  "R_Kaze_EffectSize_L",
  "R_MaxHp_Absolute_Meg_S",
  "R_MaxHp_Absolute_Meg_E",
  "R_MaxHp_Absolute_Meg_L",
  "R_HighHealthDamage_E",
  "ShadowdemonMinionDamage",
  "ShadowdemonMinionHealth",
  "ShadowdemonMinionDamageOvercharged",
  "ShadowdemonMinionHealthOvercharged",
  "MB_StickyBomb_Slow",
  "MB_Shade_PassWall",
  "MB_Crow_ProjectileSpeed",
  "MB_Rico_BulletExplode_1",
  "MB_Rico_BulletExplode_2",
  "MB_Rico_BulletExplode_3",
  "MB_Grom_BulletSize",
  "MB_Grom_AreaEffectSize",
  "MB_Grom_EffectSize",
  "MB_Griff_ProjectilSize",
  "MB_Nita_ProjectilSize",
  "MB_DragonCrowL1_ProjectilSize",
  "MB_DragonCrowL2_ProjectilSize",
  "MB_DragonCrowL3_ProjectilSize",
  "MB_Crow_FireBallAround",
  "MB_Colette_ProjectilSize",
  "SN_Spike_ProjectileSize",
  "SN_Spike_ProjectileSpeed",
  "SN_Spike_AreaEffect",
  "SN_Juju_ProjectileSize",
  "SN_Juju_AreaEffect",
  "SN_Juju_ProjectileSpeed",
  "SN_Stella_AttackRange",
  "SN_Stella_EffectSize",
  "SN_Stella_ChargeSpeed",
  "SN_AttackRange_Minus1",
  "SN_Bea_ProjectileSize",
  "SN_Bea_ProjectileSpeed",
  "SN_Colette_ProjectileSize",
  "SN_Finx_AreaEffect",
  "SN_Spike_ChargeSuper",
  "SN_Juju_ChargeSuper",
  "SN_Bea_ChargeSuper",
  "SN_Amber_ChargeSuper",
  "SN_Stella_ChargeSuper",
  "SN_ChargeSuper",
  "SN_ChargeRateNerf",
  "SN_Amber_ProjectileSize",
  "SN_HP_Buff",
  "SN_Damage_Buff",
  "SN_SpeedUpOnAtk",
  "SN_AntiBoss_Shield",
  "Mod_speedup",
  "ColtOverchargedProjectileBuff",
  "ColtOverchargedProjectileBuff2",
  "ColtBuddySp1",
  "EmzBuddySp2",
  "FrankBuddySp1",
  "MortisBuddySp1",
  "EmzBuddySp1",
  "SpikeSp1",
  "SpikeBuddySp1",
  "MortisBuddySp2",
  "ColtBuddySp2",
  "ShelllyBuddySp1",
  "ShelllyBuddySp2",
  "ShamanBuddySp1",
  "ShamanBuddySp2",
  "CrowBuddySp2",
  "CrowBuddySp1",
  "BullDude_Gadget_1",
  "BullDude_Gadget_2",
  "NinjaBuddySp2",
  "NinjaBuddySp1",
  "BaseballSP2ExtraUltiDuration",
  "BowDudeSPHiddenDuringAttackInForest",
  "BowDudeSPMineShotSpeed",
  "RedirecterStarPowerCurrentHPPoisonTrait",
  "RedirecterStarPowerSpawnPetOnTargetDeathTrait",
  "IgnoreStatusEffects",
  "GhostDeadCenterBoost",
  "SamuraiLifeSteal",
  "CrowGadgetDaggerSlow",
  "Gladiator_SpawnFireAreaOnExpire",
  "AssaultShotgunSp1_Spread",
  "AssaultShotgunSp1_Salvo",
  "Gladiator_SpawnFireAreaExplosionOnExpire",
  -- "AssaultShotgunBuddySp1",
  -- "AssaultShotgunBuddySp2",
  "GladiatorOverrideChargeUpType",
  "GladiatorOverrideChargeUpMax",
  "SwarmMeteorOverTimeLevel1",
  "SwarmShootDemonicProjectileOverTimeLevel1",
  "SwarmShootOtherProjectileOverTimeLevel1",
  "SwarmTimeBendOverTimeLevel1",
  "SwarmWhirlwindProjectileOverTimeLevel1",
  "SwarmBarleyBottleFireL1",
  "SwarmBarleyBottleFireL2",
  "SwarmWhirlwindFireL1",
  "SwarmWhirlwindFireL2",
  "SwarmHealthBoostL1",
  "SwarmHealthBoostL2",
  "SwarmHealthBoostL3",
  "SwarmDamageBoostL1",
  "SwarmDamageBoostL2",
  "SwarmDamageBoostL3",
  "SwarmBarleyBottleFireL3",
  "SwarmWhirlwindFireL3",
  "MB_FinxL1_ProjectilSize",
  "MB_FinxL2_ProjectilSize",
  "EnragerBuddySp1",
  "EnragerBuddySp2",
  "MB_FinxTowerUntargetable",
  "MB_FinxTowerAreaEffect",
  "Swarm_PickupRange_Base",
  "Swarm_MoveSpeed_Base",
  "SwarmElectroBoltFireL1",
  "SwarmElectroBoltFireL2",
  "SwarmElectroBoltFireL3",
  "SwarmElectroBoltFireL2_2",
  "SwarmElectroBoltFireL3_2",
  "SwarmFireAuraTraitL1",
  "SwarmFireAuraTraitL2",
  "SwarmFireAuraTraitL3",
  "PercenterOverchargeFollowupProjectile",
  "MB_FinxL2_AreaSize",
  "ColetteLifestealBuddyOverheal",
  "MB_FinxTowerAreaSize",
  "PercenterBuddySp1",
  "PercenterBuddySp2",
  "RockChargeUltiOnMove",
  "PercenterSp2ChargeDamageReduction",
  "ConductorSp2ChargeAmmoSteal",
  "FutureGirlTraitShieldOnMoving",
  "FutureGirlTraitShieldOnSpawn",
  "Nano_Merge_General",
  "Nano_Merge_General_Meg",
  -- "Nano_Angelo_Swap",
  "Nano_Angelo_Super_Area",
  "Nano_Angelo_Super_Damage",
  "Nano_Angelo_HoldTime",
  "Nano_Mandy_Attack_Range",
  "Nano_Mandy_Super_Size",
  "Nano_Mandy_Super_Rate",
  "Nano_Mandy_Camera_Distance",
  "Nano_Mandy_Camera_Vision",
  "Nano_Max_Projectile_Speed",
  "Nano_Max_Super_Speedup",
  "Nano_Max_Reload",
  "Nano_Kenji_Range_Slash",
  "Nano_Kenji_Range_Effect",
  "Nano_Kenji_Super_Size",
  "Nano_Kenji_Super_Teleport",
  "Nano_Kenji_Super_Rate",
  "Nano_Kenji_Heal",
  "Nano_Tick_BulleNumber",
  "Nano_Tick_PetMax_HP",
  "Nano_Tick_PetMax_Scale",
  "Nano_Tick_PetMax_Damage",
  "Nano_Tick_PetMax_BigHead",
  "Nano_Tick_PetMax_ProjectileSize",
  "Nano_Tick_Head_1",
  "Nano_Tick_Head_2",
  "Nano_Ziggy_Attack",
  "Nano_Ziggy_Super",
  "Nano_Ziggy_Slow",
  -- "Nano_Piper_Swap",
  "Nano_Piper_SuperRate",
  "Nano_Piper_SuperSpeed",
  "Nano_Piper_Attack_FarDamage",
  "Nano_Nani_Attack_Bullet",
  "Nano_Nani_Attack_Spread",
  "Nano_Nani_Attack_Damage",
  "Nano_Nani_Super_Damage",
  "Nano_Nani_Super_Time",
  "Nano_Nani_Reflect",
  "Nano_Hank_Range_1",
  "Nano_Hank_Range_2",
  "Nano_Hank_Range_3",
  "Nano_Hank_Super_BulletNumber",
  "Nano_Hank_Super_Heal",
  "Nano_Hank_Trigger",
  "Nano_Jessie_ShootTwice_1",
  "Nano_Jessie_ShootTwice_2",
  "Nano_Jessie_SuperUse",
  "Nano_Jessie_Super_MaxSpawn",
  "Nano_Jessie_Chain_1",
  "Nano_Jessie_Chain_2",
  "Nano_Melodie_Attack_Chain",
  "Nano_Melodie_Notes",
  "Nano_Melodie_SuperUse",
  "Nano_Melodie_Super_ChargeSpeed",
  "Nano_Melodie_Orbit_Faster",
  "Nano_Melodie_Orbit_Larger",
  "Nano_Mico_Range",
  "Nano_Mico_Super_Size",
  "Nano_Mico_Super_Damage",
  "Nano_Mico_Reload",
  "Nano_Gene_Chain_Number",
  "Nano_Gene_Chain_Spread",
  "Nano_Gene_Super_Range",
  "Nano_Gene_Super_Damage",
  -- "Nano_Gene_Trigger",
  "Nano_Sirius_Area_1",
  "Nano_Sirius_Area_2",
  "Nano_Sirius_Super_Max_Hord",
  "Nano_Sirius_Super_Max_Clone",
  "Nano_Sirius_Clone_HP",
  "Nano_Sirius_Clone_Size",
  -- "Nano_Sirius_Spawn_Teammate",
  "Nano_Grom_Attack_Number",
  "Nano_Grom_Chain_Distance",
  "Nano_Grom_Chain_Effect",
  "Nano_Grom_Super_Time",
  "Nano_Grom_Super_MS",
  "Nano_Grom_Size",
  "Nano_Grom_Speed",
  "Nano_Gale_Attck_MoreBullet",
  "Nano_Gale_Super_MoreBullet",
  "Nano_Gale_Freeze_Attack",
  "Nano_Gale_Freeze_Super",
  "Nano_Lou_Attack_Size",
  "Nano_Lou_Super_Size",
  "Nano_Lou_Freeze_Super",
  -- "Nano_Eve_Attack_Bullet",
  -- "Nano_Eve_Attack_ActiveTime",
  -- "Nano_Eve_Attack_Damage",
  -- "Nano_Eve_Super_1",
  -- "Nano_Eve_Super_2",
  -- "Nano_Eve_Passive",
  "Nano_Moe_Attack_Range",
  "Nano_Moe_Attack_Damage",
  "Nano_Moe_Super_Charge",
  "Nano_Moe_Drill",
  "Nano_Moe_Drill_Range",
  "Nano_Colt_Pierce",
  "Nano_Colt_Bounce_1",
  "Nano_Colt_Bounce_2",
  "Nano_Colt_Bounce_3",
  "Nano_Colt_Super_Size",
  "Nano_Colt_MoveSpeed",
  "Nano_Cordelius_Attack",
  "Nano_Cordelius_Charge",
  "Nano_Cordelius_Home_1",
  "Nano_Cordelius_Home_2",
  "Nano_Cordelius_Home_3",
  "Nano_Cordelius_Home_4",
  -- "Nano_Cordelius_Mushroom",
  "Nano_Dynamike_Attack",
  "Nano_Dynamike_SuperSize_1",
  "Nano_Dynamike_SuperSize_2",
  "Nano_Dynamike_Delay",
  "Nano_Belle_Chain_1",
  "Nano_Belle_Chain_2",
  "Nano_Belle_Super",
  "Nano_Belle_Gadget",
  "Nano_Lily_Attack_Ammo",
  "Nano_Lily_Super_Damage",
  "Nano_Lily_Super_Home_1",
  "Nano_Lily_Super_Home_2",
  "Nano_Lily_Super_Home_3",
  "Nano_Lily_Super_Home_4",
  "Nano_Lily_Gadget",
  "Nano_Primo_Range",
  "Nano_Primo_Attack_Speed",
  "Nano_Primo_Super_Size",
  "Nano_Primo_Super_Effect",
  "Nano_Primo_Charge_Ulti",
  "Nano_Primo_Charge_HC",
  -- "Nano_Rico_Trigger",
  "Nano_Rico_Super_Bounce_1",
  "Nano_Rico_Super_Bounce_2",
  "Nano_Rico_Super_Bounce_3",
  "Nano_Rico_BulletSize",
  "Nano_Clancy_Range",
  "Nano_Clancy_Super_1",
  "Nano_Clancy_Super_2",
  "Nano_Clancy_Super_3",
  "Nano_Clancy_Level",
  "Nano_Byron_HomeIn_1",
  "Nano_Byron_HomeIn_2",
  "Nano_Byron_HomeIn_3",
  "Nano_Byron_HomeIn_4",
  "Nano_Byron_Super_Size",
  "Nano_Byron_Super_Push",
  "Nano_Byron_Super_Projectile",
  "Nano_Byron_HealCharge",
  "Nano_Crow_Attack_Spread",
  "Nano_Crow_Attack_Bullet",
  "Nano_Crow_Super",
  "Nano_Crow_StatusEffect",
  "Nano_Lumi_Attack_Size",
  "Nano_Lumi_Item_Size",
  "Nano_Lumi_Super_Size",
  "Nano_Lumi_Projectile_Speed",
  "Nano_Bea_Attack_1",
  "Nano_Bea_Attack_2",
  "Nano_Bea_Attack_3",
  "Nano_Bea_Attack_4",
  "Nano_Bea_Chain_Slow",
  "Nano_Bea_Super_Damage",
  "Nano_Bea_Super_Charge",
  "Nano_Bea_Shield",
  "Nano_Shade_AttackRange_1",
  "Nano_Shade_AttackRange_2",
  "Nano_Shade_SuperLastTime",
  "Nano_Shade_Charge",
  "Nano_8Bit_ProjectileSpeed",
  "Nano_8Bit_AreaSize",
  "Nano_8Bit_MoveSpeed",
  "Nano_Bibi_Range_1",
  "Nano_Bibi_Range_2",
  "Nano_Bibi_Super_1",
  "Nano_Bibi_Super_2",
  "Nano_Bibi_Super_3",
  "Nano_Bibi_Shield_1",
  "Nano_Bibi_Shield_2",
  "Nano_Jacky_Attack_Range",
  "Nano_Jacky_Super_Shield",
  "Nano_Jacky_Charge",
  "Nano_Bo_Range",
  "Nano_Bo_Damage",
  "Nano_Bo_Mine_1",
  "Nano_Bo_Mine_2",
  "Nano_Bo_Charge",
  "Nano_Bo_InfinateMine",
  -- "Nano_Pam_HomeIn",
  "Nano_Pam_AreaSize",
  "Nano_Pam_Health",
  "Nano_Pam_Size",
  "Nano_Meeple_HomeInMore",
  "Nano_Meeple_Area_1",
  "Nano_Meeple_Area_2",
  "Nano_Meeple_Duration",
  "Nano_Finx_Attack",
  "Nano_Finx_Area",
  -- "Nano_Finx_FollowArea",
  "Nano_Finx_Duration",
  "Nano_Rosa_SpawnBushOnAttack",
  "Nano_Rosa_Shield",
  "Nano_Rosa_Effect",
  "Nano_Rosa_Bush_Speed",
  "Nano_Rosa_Bush_Damage",
  "Nano_Jae_Attack",
  "Nano_Jae_Charge",
  "Nano_Jae_Area",
  "Nano_Chuck_Attack_Size",
  "Nano_Chuck_Super_Damage",
  "Nano_Chuck_Super_Speed",
  "Nano_Chuck_Super_Effect",
  "Nano_Chuck_Pole",
  "Nano_Chuck_Charge",
  "Nano_Penny_Chain_1",
  "Nano_Penny_Chain_2",
  "Nano_Penny_Super_1",
  "Nano_Penny_Super_2",
  "Nano_Penny_AttackSpeed",
  "Nano_Nita_Attack",
  "Nano_Nita_Super_Auto",
  "Nano_Nita_Bear_HP",
  "Nano_Nita_Bear_Size",
  -- "Nano_Darryl_Attack_Swap",
  "Nano_Darryl_Super_Time",
  "Nano_Darryl_Super_Damage",
  "Nano_Darryl_Cons_Shield",
  "Nano_Shelly_Attack_Range",
  "Nano_Shelly_Attack_Spread",
  "Nano_Shelly_Super_Double_1",
  "Nano_Shelly_Super_Double_2",
  "Nano_Shelly_Super_Double_3",
  "Nano_Shelly_Super_Double_4",
  "Nano_Shelly_Heal",
  "Nano_Bull_Attack_Pattern",
  "Nano_Bull_Attack_Spread",
  "Nano_Bull_ChargeSpeed",
  "Nano_Bull_Execute",
  "Nano_Poco_Spread",
  "Nano_Poco_Bullet",
  "Nano_Poco_Pattern",
  "Nano_Poco_Super_Heal",
  "Nano_Poco_Super_Range",
  "Nano_Poco_Super_Heal_Self",
  "Nano_Poco_Damage",
  "Nano_Olli_Bullet",
  "Nano_Olli_Spread",
  "Nano_Olli_Damage",
  "Nano_Olli_Taunt",
  "Nano_Olli_Gadget",
  -- "Nano_Pearl_Swap",
  "Nano_Pearl_Attack",
  "Nano_Pearl_Spread",
  "Nano_Pearl_Projectile",
  "Nano_Pearl_Super_Area",
  "Nano_Pearl_Heat",
  "Nano_Berry_Attack_Size_1",
  "Nano_Berry_Attack_Size_2",
  "Nano_Berry_Super_Shield",
  "Nano_Berry_Super_Effect",
  "Nano_Berry_Super_Range",
  "Nano_Berry_Heal_Self",
  "Nano_Berry_Heal_Team",
  "Nano_Charlie_Projectile_Speed",
  "Nano_Charlie_Projectile_Size",
  "Nano_Charlie_Cocoon_HealthBack",
  "Nano_Charlie_Cocoon_Size",
  "Nano_Charlie_Cocoon_HP",
  "Nano_Charlie_Spider",
  "Nano_Gus_Size",
  "Nano_Gus_Size_Item",
  "Nano_Gus_Super_Shield_Amount",
  "Nano_Gus_Super_Shield_Decay",
  "Nano_Gus_Super_Shield_Size",
  "Nano_Gus_Balloon_1",
  "Nano_Gus_Balloon_2",
  "Nano_Gus_Balloon_3",
  "Nano_Stu_Attack_Reload",
  "Nano_Stu_Super",
  "Nano_Stu_HC",
  "Nano_Glowy_LOS",
  "Nano_Glowy_Super_Status",
  "Nano_Glowy_Tether_Double",
  "Nano_Tara_Attack_Bullet",
  "Nano_Tara_Attack_Spread",
  "Nano_Tara_Super_1",
  "Nano_Tara_Super_2",
  -- "Nano_Tara_Spawn",
  "Nano_Buzz_Attack_Range",
  "Nano_Buzz_Attack_Size",
  "Nano_Buzz_Super_Range",
  "Nano_Buzz_Super_Speed",
  "Nano_Buzz_Super_Projectile",
  "Nano_Buzz_HC_Rate",
  "Nano_Buzz_HC_Time",
  "Nano_Pierce_ChargeShoot_Size",
  "Nano_Pierce_ChargeShoot_Pierce",
  "Nano_Pierce_Super_Size",
  "Nano_Pierce_DropShell",
  "Nano_Juju_Damage",
  "Nano_Juju_Range",
  "Nano_Juju_Area",
  "Nano_Juju_Grigri_Speed",
  "Nano_Juju_Grigri_Attack",
  "Nano_Juju_Grigri_Size",
  "Nano_Juju_AutoCharge",
  "Nano_Frank_Attack",
  "Nano_Frank_Spread",
  "Nano_Frank_Super_Range",
  "Nano_Frank_HP",
  "Nano_Frank_Scale",
  "Nano_Frank_Speed",
  "Nano_Larry_Size_1",
  "Nano_Larry_Size_2",
  "Nano_Larry_Pet_1",
  "Nano_Larry_Pet_2",
  "Nano_Larry_Pet_3",
  "Nano_Larry_Reborn",
  "Nano_Squeak_Attack",
  "Nano_Squeak_SpawnArea",
  "Nano_Squeak_Size_1",
  "Nano_Squeak_Size_2",
  "Nano_Colette_Size",
  "Nano_Colette_Super_Area",
  "Nano_Colette_Super_Damage",
  "Nano_Colette_Damage",
  "Nano_Willow_Size_1",
  "Nano_Willow_Size_2",
  "Nano_Willow_Super_Pierce",
  "Nano_Willow_Super_Range",
  "Nano_Willow_Damage",
  "Nano_Buster_Spread",
  "Nano_Buster_Bullet",
  "Nano_Buster_ActiveTime",
  "Nano_Buster_ReflectDamage",
  "Nano_Chester_Attack",
  "Nano_Chester_Charge_1",
  "Nano_Chester_Charge_2",
  "Nano_Chester_HC",
  "Nano_Kit_Range_1",
  "Nano_Kit_Range_2",
  "Nano_Kit_Attach",
  "Nano_Kit_PowerCubeOnKill",
  "Nano_Najia_Pierce",
  "Nano_Najia_Range",
  "Nano_Najia_HealthBack",
  "Nano_Najia_HP",
  -- "Nano_Najia_Trigger",
  "Nano_Draco_Range",
  "Nano_Draco_Time",
  "Nano_Draco_Fire",
  "Nano_Mortis_Range",
  "Nano_Mortis_DashSpeed",
  "Nano_Mortis_Super_Rate",
  "Nano_Mortis_Heal",
  "Nano_Sandy_Range",
  "Nano_Sandy_Super",
  -- "Nano_Sandy_Trigger",
  -- "Nano_Sandy_Trigger_Effect",
  "Nano_Janet_Range",
  "Nano_Janet_Super_Attack",
  "Nano_Janet_Jetpack",
  "Nano_Bolt_Attack",
  "Nano_Bolt_Super_Area",
  "Nano_Bolt_Super_Last",
  "Nano_Bolt_Super_Effect_Speed",
  "Nano_Bolt_Speedup",
  "Nano_Starrnova_Attack_Range_1",
  "Nano_Starrnova_Attack_Range_2",
  "Nano_Starrnova_Super_Range",
  "Nano_Starrnova_Super_Effect",
  "Nano_Starrnova_Duration",
  "Nano_Wendy_Pierce",
  "Nano_Wendy_Pet_HP",
  "Nano_Wendy_Pet_Size",
  "Nano_Wendy_Shield_Reload",
  "Nano_Nori_Attack",
  "Nano_Nori_Super",
  "Nano_Nori_Fish",
  "Nano_Trunk_Attack_Area",
  "Nano_Trunk_Super_Range",
  -- "Nano_Trunk_Trigger",
  "Nano_Spike_BulletMore",
  "Nano_Spike_Super_1",
  "Nano_Spike_Super_2",
  "Nano_Spike_Revive",
  "Nano_Otis_ActiveTime",
  "Nano_Otis_Super_Pierce_1",
  "Nano_Otis_Super_Pierce_2",
  "Nano_Otis_Duration",
  "Nano_Ash_Homein_1",
  "Nano_Ash_Homein_2",
  "Nano_Ash_Homein_3",
  "Nano_Ash_Homein_4",
  "Nano_Ash_PetNumber_1",
  "Nano_Ash_PetNumber_2",
  "Nano_Ash_Rage",
  "Nano_Carl_Attack_Size",
  "Nano_Carl_Super_Area_1",
  "Nano_Carl_Super_Area_2",
  "Nano_Carl_Super_Speed",
  "Nano_Carl_Fire",
  "Nano_Sprout_Attack_Size",
  "Nano_Sprout_Attack_Area",
  "Nano_Sprout_Super_Damage",
  "Nano_Sprunt_Passive",
  "Nano_Gray_Attack",
  "Nano_Gray_Portal",
  "Nano_Gray_Charge",
  "Nano_Gray_Trigger",
  "Nano_Mrp_Attack_Size",
  "Nano_Mrp_Attack_Area",
  "Nano_Mrp_Super_Passive",
  "Nano_Mrp_Spawn",
  "Nano_Bonnie_Attack",
  "Nano_Bonnie_Charge_1",
  "Nano_Bonnie_Charge_2",
  "Nano_Bonnie_Speed",
  "Nano_Ruff_Bullet",
  "Nano_Ruff_Super_Damage",
  "Nano_Ruff_Super_Size",
  "Nano_Ruff_HC",
  "Nano_Barley_Attack_Size_1",
  "Nano_Barley_Attack_Size_2",
  "Nano_Barley_Super_Time_1",
  "Nano_Barley_Super_Time_2",
  "Nano_Barley_Poison",
  -- "Nano_RT_Swap",
  "Nano_RT_Bullet_Area",
  "Nano_RT_Mark_Damage",
  "Nano_Fang_Attack_Area",
  "Nano_Fang_Attack_Chain_1",
  "Nano_Fang_Attack_Chain_2",
  "Nano_Fang_Attack_Chain_3",
  "Nano_Fang_Super_Shield",
  "Nano_Fang_Super_Effect",
  "Nano_Fang_Heal_OnKill",
  "Nano_Mina_Heal",
  "Nano_Mina_Shield",
  "Nano_Mina_Reload",
  "Nano_Kaze_Attack_1",
  "Nano_Kaze_Attack_2",
  "Nano_Kaze_Attack_3",
  "Nano_Kaze_Range_1",
  "Nano_Kaze_Range_2",
  "Nano_Kaze_Super",
  "Nano_Kaze_Shield",
  "Nano_Leon_Attack",
  "Nano_Leon_Super_1",
  "Nano_Leon_Super_2",
  "Nano_Leon_Super_3",
  "Nano_Leon_Kill",
  "Nano_Lola_Attack",
  "Nano_Lola_Pet_1",
  "Nano_Lola_Pet_2",
  "Nano_Lola_Special",
  "Nano_Doug_Attack",
  "Nano_Doug_Super",
  -- "Nano_Doug_Item",
  -- "Nano_Alli_Reload",
  -- "Nano_Alli_Damage",
  "Nano_Alli_Water",
  -- "Nano_Sam_Attack",
  "Nano_Sam_Slow",
  "Nano_Sam_Charge",
  "Nano_Damian_Range",
  "Nano_Damian_Size",
  "Nano_Damian_Super",
  "Nano_Damian_FirePunch",
  -- "Nano_Maisie_Swap",
  "Nano_Maisie_Super",
  "Nano_Maisie_Super_Charge",
  -- "Nano_Maisie_Dash",
  "Nano_Gigi_MaxAmmo",
  "Nano_Gigi_Super_1",
  "Nano_Gigi_Super_2",
  "Nano_Gigi_Super_3",
  "Nano_Gigi_Charge_Area_1",
  "Nano_Gigi_Charge_Area_2",
  "Nano_Edgar_Range",
  "Nano_Edgar_Size",
  "Nano_Edgar_Effect",
  "Nano_Edgar_Super_Charge",
  "Nano_Edgar_Super_HC",
  "Nano_Edgar_Gadget",
  "Nano_Emz_Attack",
  "Nano_Emz_Attack_Effect",
  "Nano_Emz_Super",
  "Nano_Emz_Special",
  "Nano_Brock_Area_1",
  "Nano_Brock_Area_2",
  "Nano_Brock_Super",
  "Nano_Brock_Gadget",
  "Nano_Griff_Range",
  "Nano_Griff_Super",
  "Nano_Griff_Special",
  "Nano_Meg_Attack",
  "Nano_Meg_Spread",
  "Nano_Meg_Super_1",
  "Nano_Meg_Super_2",
  "Nano_Meg_Super_3",
  "Nano_Meg_HP",
  "Nano_Meg_Scale",
  "Nano_Amber_Range",
  "Nano_Amber_Super_1",
  "Nano_Amber_Super_2",
  "Nano_Amber_Reload",
  "Nano_Surge_Attack",
  "Nano_Surge_Super_Range",
  "Nano_Surge_Super_Area_1",
  "Nano_Surge_Super_Area_2",
  "Nano_Surge_Super_Slow",
  "Nano_Surge_Trait",
  "ArcadeStarpower1PetComponent",
  "ArcadeStarpower2ForTeammates",
  "ArcadeGadget1HealSelf",
  "ArcadeGadget1HealPet",
  "KatanaKidUltiAreaSizeBoost",
  "MechaDudeSpSpeedWithShield",
  "FutureGirlSP1TurretAreaEffectEnemySlowdown",
  "TrickshotDudeDynamicGadgetExplosionBullets",
  "TrickshotDudeAddUltiPercentOnBounceHit",
  "SpeedyBuddyRewindGiveAmmo",
  "SpeedyBuddyRewindHealAllies",
  "SpeedyBuddyAreaAdditionalStatus",
  "FutureGirlShieldDamageEnemy",
  "PowerLevelerStartWithUltiRespawn",
  "PowerLevelerStartWithUltiInitial",
  "PowerLevelerSpeedBurstOnUltiAt2",
  "PowerLevelerBouncyProjectilesSp",
  "PowerLevelerBouncyProjectilesSpBuddy",
  "RocketGirlSP1SpeedBuff",
  "RocketGirlSP2ChargeUpTypeOverride",
  "RocketGirlSP2ChargeUpMaxOverride",
  "RocketGirlAddCastingRangeSP2",
  "SpeedyChargeUltiOnMove",
  "MB_KatanaKidFishSpawnerUntargetable",
  "MB_KatanaKidFishSpawnerAreaSize",
  "AttractorProjectileMagnet_SteerStrength",
  "AttractorProjectileMagnet_SteerIgnoreTicks",
  "AttractorProjectileMagnet_SteerHomeDistance",
  "AttractorProjectileMagnet_OverrideTravelType",
  "HunterSurvivor_HP",
  "HunterSurvivor_Scale",
  "HunterSurvivor_Damage",
  "HunterSurvivor_Speed",
  "HunterSurvivor_Revive",
  "HunterSurvivor_Show",
  "HunterSurvivor_Show_Survivor",
  "DeadMariachiProjectileHealPassive",
  "PocoBuddySp1",
  "PocoBuddySp2",
  "LuchadorThrowLandDamageEffect",
  "ConductorStartWithFullUlti",
  "SoulCollectorHomingSoulsSpBuddy",
  "SoulCollectorSpeedAndDamageBoostAllySpBuddy",
  "SoulCollectorDamageBoostAllySp",
  "SoulCollectorKnockbackSoulSpawnSoulOnHit",
  "SoulCollectorExplodeSoulsLoseAmmo",
  "ConductorSlowSp",
  "ConductorPoleFireBuddy",
  "ConductorChargeSpeedBuddy",
  "AttractorOrbitSpeedStarPower",
  "GhostDeadCenterGadgetCooldownBuddy",
  "GhostLongerIncorporealBuddy",
  "GhostDeadCenterBoostOvercharged",
  "FireDudeSpBuddyPetrolStatus",
  "FireDudeSpPetrolStatusEnemy",
  "FireDudeLongerFireBuddy",
  "BullDudeBuddyTakedownShield",
  "DisableVisionInBush",
  "MB_Duo_Shield",
  "MB_CCImmunity",
  "MB_Duo_ProjectilSize_5P",
  "MB_Duo_ProjectilSize_20P",
  "MB_Duo_AreaEffectSize_5P",
  "MB_Duo_AreaEffectSize_20P"
}

-- Strips a trailing run of digits from a trait name, e.g. "elPrimo2" -> "elPrimo",
-- "Angels1_1" -> "Angels1_". Returns nil if the name doesn't end with a number.
local function stripTrailingNumber(name)
    return name:match("^(.-)%d+$")
end

-- Remembers the most recent trait grant message for each player (keyed by
-- player index), so that if that player later turns out to have crashed, we
-- can log which trait(s) they were given right before the crash.
local lastTraitMessage = {}

-- Picks a random trait and grants it to the player's character. If the picked
-- trait ends with a number, every trait sharing that base name is granted too.
local function grantRandomTrait(p, char)
    local traits = char.traits
    local randomTrait = server:getRandomInt(1, #TRAITS)
    local traitName = TRAITS[randomTrait]
    local base = stripTrailingNumber(traitName)

    if base then
        -- Trait ends with a number: grant every trait that shares the same base name.
        local grantedNames = {}
        for _, t in ipairs(TRAITS) do
            if stripTrailingNumber(t) == base then
                traits:add(lookup(108, t))
                table.insert(grantedNames, t)
            end
        end
        local message = "Player " .. p.index .. " received traits: " .. table.concat(grantedNames, ", ")
        lastTraitMessage[p.index] = message
        log(message)
    else
        -- Trait doesn't end with a number: grant just that one trait as before.
        traits:add(lookup(108, traitName))
        local message = "Player " .. p.index .. " received trait: " .. traitName
        lastTraitMessage[p.index] = message
        log(message)
    end
end

-- Tracks each player's alive state from the previous time they were checked,
-- keyed by player index. A missing entry means "not checked yet" (used to grant
-- the initial trait the first time a player is processed).
local wasAlive = {}

-- Cycles through players, one per tick, so only a single player is updated
-- on any given tick (including their very first, initial trait grant).
local nextPlayerIndex = 0

-- === Crash detection ===
-- If a player's position (p.x, p.y) doesn't change for this many ticks while
-- they're alive, we treat that as a client crash caused by whatever trait
-- they were last given.
local CRASH_STALL_TICKS = 200

-- Once a crash is detected, we wait this many ticks before force-finishing
-- the battle.
local CRASH_FINISH_DELAY_TICKS = 3

-- Per-player last known position and the tick it last changed, keyed by
-- player index.
local lastPos = {}
local lastMoveTick = {}

-- Set once a crash has been detected, so all other tick logic stops running.
local crashDetected = false
local crashDetectedTick = nil

function tick()
    -- Once a crash trait has been detected, do nothing else except wait for
    -- the finish delay, then end the battle.
    if crashDetected then
        if server.tick - crashDetectedTick >= CRASH_FINISH_DELAY_TICKS then
            server:debugFinishBattle(0)
        end
        return
    end

    -- Check every alive player's position each tick for a movement stall,
    -- but only once the match is past tick 500 (avoids false positives
    -- while players are still spawning in / not yet moving).
    if server.playersCount > 0 and server.tick > 500 then
        for i = 0, server.playersCount - 1 do
            local player = server:getClientInfo(i)
            if player ~= nil and player.isAlive then
                local prev = lastPos[player.index]
                if prev == nil or prev.x ~= player.x or prev.y ~= player.y then
                    lastPos[player.index] = { x = player.x, y = player.y }
                    lastMoveTick[player.index] = server.tick
                else
                    local stalledTicks = server.tick - lastMoveTick[player.index]
                    if stalledTicks >= CRASH_STALL_TICKS then
                        crashDetected = true
                        crashDetectedTick = server.tick
                        local traitMessage = lastTraitMessage[player.index] or
                            ("Player " .. player.index .. " has no recorded trait grant")
                        log("Crash detected: " .. traitMessage ..
                            " (no movement for " .. CRASH_STALL_TICKS .. " ticks)")
                        break
                    end
                end
            end
        end
    end

    if crashDetected then
        -- Stop all other code this tick; debugFinishBattle fires after the
        -- delay above on a later tick.
        return
    end

    if server.playersCount > 0 then
        local i = nextPlayerIndex % server.playersCount
        nextPlayerIndex = i + 1

        local p = server:getClientInfo(i)
        local isAliveNow = p.isAlive
        local previousState = wasAlive[p.index]

        if isAliveNow and (previousState == nil or previousState == false) then
            -- Either the first time we've seen this player (initial grant),
            -- or they just respawned (were dead, are now alive again).
            local char = server.objectManager:getObject(p.objectId)
            if char ~= nil then
                grantRandomTrait(p, char)
            end
        end

        
        if isAliveNow and server.tick % 50 == i and server.tick > 100 then
            local char = server.objectManager:getObject(p.objectId)
            if char ~= nil then
                grantRandomTrait(p, char)
            end
        end

        wasAlive[p.index] = isAliveNow
    end
end