--!strict
-- Generated by NB Scripting Tools. Do not edit manually.
-- Entry: TraficLight/src/main.luau

local __NBS_MODULES = {}
local __NBS_CACHE = {}
local __NBS_LOADED = {}
local __NBS_LOADING = {}

local function __NBS_REQUIRE(moduleName: string)
    if __NBS_LOADED[moduleName] then
        return __NBS_CACHE[moduleName]
    end
    if __NBS_LOADING[moduleName] then
        error(`Циклическая зависимость: {moduleName}`)
    end
    local factory = __NBS_MODULES[moduleName]
    if factory == nil then
        error(`Модуль не найден: {moduleName}`)
    end
    __NBS_LOADING[moduleName] = true
    local result = factory(__NBS_REQUIRE)
    __NBS_LOADING[moduleName] = nil
    if result == nil then result = true end
    __NBS_CACHE[moduleName] = result
    __NBS_LOADED[moduleName] = true
    return result
end

-- ============================================================
-- Module: TraficLight/src/config
-- Source: TraficLight/src/config.luau
-- ============================================================
__NBS_MODULES["TraficLight/src/config"] = function(require)
    -- Все длительности в тиках: 20 тиков = 1 секунда.
    local Config = {
    	server = {
    		skipIntro = true,
    		disablePoison = true,
    	},
    	green = {
    		minTicks = 10 * 20,
    		maxTicks = 15 * 20,
    	},
    	red = {
    		minTicks = 50,
    		maxTicks = 150,
    	},
    	chat = {
    		enabled = true,
    		greenMessage = "<c00ff00>GREEN LIGHT</c>",
    		redMessage = "<cff0000>RED LIGHT</c>",
    		rulesMessage = "TRAFFIC LIGHT RULES\n"
    			.. "<c00ff00>GREEN: You can move and turn.</c>\n"
    			.. "<cff0000>RED: Stay completely still. Moving or turning kills you!</c>\n"
    			.. "Warning effects appear before RED and when GREEN starts.\n"
    			.. "Cross = STOP. Check mark = GO.",
    	},
    	movement = {
    		-- Допустимое суммарное смещение от точки начала красного.
    		tolerance = 0,
    		-- Поворот головы или ног тоже считается нарушением. Допуск в градусах.
    		checkRotation = true,
    		angleTolerance = 0,
    		checkHeight = true,
    		includeBots = true,
    	},
    	warning = {
    		enabled = true,
    		beforeRedTicks = 30,
    		-- На сколько тиков сокращать предупреждение в каждом следующем цикле (0 — отключить).
    		decreasePerCycleTicks = 1,
    		minBeforeRedTicks = 10,
    		dataType = 17,
    		name = "MegaBossWarning360",
    		damageBonus = 0,
    		applyOwnerBuffs = false,
    		followOwner = false,
    		z = 0,
    	},
    	spray = {
    		enabled = true,
    		dataType = 18,
    		name = "Spray",
    		redIndex = 5,
    		greenIndex = 4,
    		greenTicks = 20,
    		z = 0,
    	},
    	death = {
    		-- Добавляется к текущему HP и HP расходуемого щита.
    		extraDamage = 1000000,
    		ultiCharge = 0,
    		hasIndication = true,
    		hasHighlight = false,
    		forceProtected = true,
    		forceAll = true,
    		makeVisible = true,
    		disallowSpawns = true,
    		extraValue = 0,
    		origin = AttackOrigin.UNKNOWN,
    	},
    }
    
    assert(Config.green.minTicks >= 1 and Config.green.maxTicks >= Config.green.minTicks, "Invalid green duration")
    assert(Config.red.minTicks >= 1 and Config.red.maxTicks >= Config.red.minTicks, "Invalid red duration")
    assert(
    	Config.warning.beforeRedTicks >= 0 and Config.warning.beforeRedTicks <= Config.green.minTicks,
    	"Invalid warning time"
    )
    assert(Config.spray.greenTicks >= 0, "Invalid spray duration")
    assert(Config.warning.decreasePerCycleTicks >= 0, "Invalid warning decrease")
    assert(
    	Config.warning.minBeforeRedTicks >= 0 and Config.warning.minBeforeRedTicks <= Config.warning.beforeRedTicks,
    	"Invalid minimum warning time"
    )
    assert(Config.movement.tolerance >= 0, "Invalid movement tolerance")
    assert(Config.movement.angleTolerance >= 0 and Config.movement.angleTolerance <= 180, "Invalid angle tolerance")
    
    return Config
end

-- ============================================================
-- Module: TraficLight/src/phases
-- Source: TraficLight/src/phases.luau
-- ============================================================
__NBS_MODULES["TraficLight/src/phases"] = function(require)
    local Config = require("TraficLight/src/config")
    
    local Phases = {}
    local Phase = {
    	Green = "green",
    	Red = "red",
    }
    
    local phase = Phase.Green
    local phaseStart: number? = nil
    local phaseEnd = 0
    local warningSent = false
    local beforeRedTicks = Config.warning.beforeRedTicks
    
    function Phases.update(now: number): boolean
    	if phaseStart ~= nil and now < phaseEnd then
    		return false
    	end
    
    	if phaseStart ~= nil then
    		phase = phase == Phase.Green and Phase.Red or Phase.Green
    	end
    
    	local duration = phase == Phase.Green and Config.green or Config.red
    	phaseStart = now
    	-- Верхняя граница getRandomInt исключается.
    	phaseEnd = now + server:getRandomInt(duration.minTicks, duration.maxTicks + 1)
    	warningSent = false
    	return true
    end
    
    function Phases.isGreen(): boolean
    	return phase == Phase.Green
    end
    
    function Phases.shouldWarn(now: number, phaseChanged: boolean): boolean
    	local warningDue = Phases.isGreen()
    		and not warningSent
    		and now >= phaseEnd - beforeRedTicks
    
    	if warningDue then
    		warningSent = true
    		beforeRedTicks = math.max(
    			Config.warning.minBeforeRedTicks,
    			beforeRedTicks - Config.warning.decreasePerCycleTicks
    		)
    	end
    	return (phaseChanged and Phases.isGreen()) or warningDue
    end
    
    function Phases.getSprayIndex(now: number): number?
    	if phase == Phase.Red then
    		return Config.spray.redIndex
    	end
    	if phaseStart ~= nil and now - phaseStart < Config.spray.greenTicks then
    		return Config.spray.greenIndex
    	end
    	return nil
    end
    
    return Phases
end

-- ============================================================
-- Module: TraficLight/src/types
-- Source: TraficLight/src/types.luau
-- ============================================================
__NBS_MODULES["TraficLight/src/types"] = function(require)
    -- @nbscripting-global-types
    
    type PlayerState = {
    	character: LogicCharacter,
    	x: number,
    	y: number,
    	z: number,
    	angleHead: number,
    	angleLegs: number,
    	condemned: boolean,
    	spray: LogicItem?,
    	sprayIndex: number?,
    }
    
    return {}
end

-- ============================================================
-- Module: TraficLight/src/signals
-- Source: TraficLight/src/signals.luau
-- ============================================================
__NBS_MODULES["TraficLight/src/signals"] = function(require)
    local Config = require("TraficLight/src/config")
    local Types = require("TraficLight/src/types")
    
    type PlayerState = Types.PlayerState
    
    local Signals = {}
    local warningData = Config.warning.enabled and lookup(Config.warning.dataType, Config.warning.name)
    local sprayData = Config.spray.enabled and lookup(Config.spray.dataType, Config.spray.name)
    
    function Signals.warning(character: LogicCharacter): ()
    	if not warningData then
    		return
    	end
    
    	local options = Config.warning
    	local effect = character:spawnCirclingAreaEffect(
    		options.damageBonus,
    		warningData :: AreaEffectData,
    		AttackOrigin.UNKNOWN,
    		options.applyOwnerBuffs,
    		options.followOwner
    	)
    	effect:setPosition(character.x, character.y, options.z)
    end
    
    function Signals.clear(state: PlayerState): ()
    	if state.spray ~= nil and state.spray:isAlive() then
    		state.spray:destroy()
    	end
    	state.spray = nil
    	state.sprayIndex = nil
    end
    
    function Signals.update(state: PlayerState, index: number?): ()
    	if not sprayData or index == nil then
    		Signals.clear(state)
    		return
    	end
    	local character = state.character
    	if state.sprayIndex ~= index or state.spray == nil or not state.spray:isAlive() then
    		Signals.clear(state)
    		local spray = createObject(sprayData) :: LogicItem
    		spray:setIndex(character.index, character.team)
    		spray.sprayDataIndex = index
    		spray:setPosition(character.x, character.y, Config.spray.z)
    		server.objectManager:addObject(spray)
    		state.spray = spray
    		state.sprayIndex = index
    	else
    		state.spray:setPosition(character.x, character.y, Config.spray.z)
    	end
    end
    
    return Signals
end

-- ============================================================
-- Module: TraficLight/src/movement
-- Source: TraficLight/src/movement.luau
-- ============================================================
__NBS_MODULES["TraficLight/src/movement"] = function(require)
    local Config = require("TraficLight/src/config")
    local Types = require("TraficLight/src/types")
    
    type PlayerState = Types.PlayerState
    
    local Movement = {}
    local toleranceSquared = Config.movement.tolerance * Config.movement.tolerance
    
    function Movement.savePose(state: PlayerState): ()
    	local character = state.character
    	state.x = character.x
    	state.y = character.y
    	state.z = character.z
    	state.angleHead = character.angleHead
    	state.angleLegs = character.angleLegs
    end
    
    local function angleDifference(current: number, previous: number): number
    	return math.abs((current - previous + 180) % 360 - 180)
    end
    
    function Movement.hasMoved(state: PlayerState): boolean
    	local character = state.character
    	local options = Config.movement
    	local dx = character.x - state.x
    	local dy = character.y - state.y
    	local dz = options.checkHeight and character.z - state.z or 0
    
    	if dx * dx + dy * dy + dz * dz > toleranceSquared then
    		return true
    	end
    	if not options.checkRotation then
    		return false
    	end
    
    	return angleDifference(character.angleHead, state.angleHead) > options.angleTolerance
    		or angleDifference(character.angleLegs, state.angleLegs) > options.angleTolerance
    end
    
    return Movement
end

-- ============================================================
-- Module: TraficLight/src/damage
-- Source: TraficLight/src/damage.luau
-- ============================================================
__NBS_MODULES["TraficLight/src/damage"] = function(require)
    local Config = require("TraficLight/src/config")
    
    local Damage = {}
    
    function Damage.kill(character: LogicCharacter): ()
    	local options = Config.death
    	character:takeDamage(
    		character.index,
    		options.extraDamage,
    		options.ultiCharge,
    		character,
    		nil,
    		options.hasIndication,
    		options.hasHighlight,
    		character.x,
    		character.y,
    		nil,
    		options.forceProtected,
    		options.origin,
    		options.forceAll,
    		options.makeVisible,
    		options.disallowSpawns,
    		options.extraValue
    	)
    end
    
    return Damage
end

-- ============================================================
-- Module: TraficLight/src/players
-- Source: TraficLight/src/players.luau
-- ============================================================
__NBS_MODULES["TraficLight/src/players"] = function(require)
    local Config = require("TraficLight/src/config")
    local Signals = require("TraficLight/src/signals")
    local Movement = require("TraficLight/src/movement")
    local Damage = require("TraficLight/src/damage")
    local Phases = require("TraficLight/src/phases")
    local Types = require("TraficLight/src/types")
    
    type PlayerState = Types.PlayerState
    
    local Players = {}
    local players: { [number]: PlayerState } = {}
    
    local function getCharacter(index: number, state: PlayerState?): LogicCharacter?
    	local client = server:getClientInfo(index)
    	local character = state and state.character
    
    	if character == nil or character.id ~= client.objectId then
    		if state ~= nil then
    			Signals.clear(state)
    		end
    		local object = client.objectId >= 0 and server.objectManager:getObject(client.objectId) or nil
    		character = nil
    		if object ~= nil and object:getType() == 0 then
    			character = object :: LogicCharacter
    		end
    	end
    
    	if character == nil or character.type ~= CharacterType.HERO or not character:isAlive() then
    		return nil
    	end
    	if character.isBot and not Config.movement.includeBots then
    		return nil
    	end
    	return character
    end
    
    local function updatePlayer(index: number, phaseChanged: boolean, showWarning: boolean, sprayIndex: number?): ()
    	local state = players[index]
    	local character = getCharacter(index, state)
    
    	if character == nil then
    		if state ~= nil then
    			Signals.clear(state)
    		end
    		players[index] = nil
    		return
    	end
    
    	if state == nil then
    		state = {
    			character = character,
    			x = character.x,
    			y = character.y,
    			z = character.z,
    			angleHead = character.angleHead,
    			angleLegs = character.angleLegs,
    			condemned = false,
    			spray = nil,
    			sprayIndex = nil,
    		}
    		players[index] = state
    	end
    	state.character = character
    
    	if Phases.isGreen() or phaseChanged then
    		Movement.savePose(state)
    	elseif Movement.hasMoved(state) then
    		state.condemned = true
    	end
    
    	if state.condemned then
    		-- Повторяем, если временная защита отклонила предыдущий урон.
    		Damage.kill(character)
    		Signals.clear(state)
    		return
    	end
    
    	if showWarning then
    		Signals.warning(character)
    	end
    	Signals.update(state, sprayIndex)
    end
    
    function Players.update(phaseChanged: boolean, showWarning: boolean, sprayIndex: number?): ()
    	for index = 0, server.playersCount - 1 do
    		updatePlayer(index, phaseChanged, showWarning, sprayIndex)
    	end
    end
    
    function Players.clear(): ()
    	for _, state in pairs(players) do
    		Signals.clear(state)
    	end
    end
    
    return Players
end

-- ============================================================
-- Module: TraficLight/src/main
-- Source: TraficLight/src/main.luau
-- ============================================================
__NBS_MODULES["TraficLight/src/main"] = function(require)
    local Config = require("TraficLight/src/config")
    local Phases = require("TraficLight/src/phases")
    local Players = require("TraficLight/src/players")
    local started = false
    
    server.hasIntroSkip = Config.server.skipIntro
    server.hasPoisonDisabled = Config.server.disablePoison
    
    function tick(): ()
    	if server.isBattleEnded then
    		Players.clear()
    		return
    	end
    	if not server:isIntroFinished() then
    		return
    	end
    
    	local now = server.tick
    	if not started then
    		started = true
    		if Config.chat.enabled then
    			log(Config.chat.rulesMessage)
    		end
    	end
    
    	local phaseChanged = Phases.update(now)
    	if phaseChanged and Config.chat.enabled then
    		log(Phases.isGreen() and Config.chat.greenMessage or Config.chat.redMessage)
    	end
    	local showWarning = Phases.shouldWarn(now, phaseChanged)
    	local sprayIndex = Phases.getSprayIndex(now)
    
    	Players.update(phaseChanged, showWarning, sprayIndex)
    end
end

__NBS_REQUIRE("TraficLight/src/main")
